name: delivery_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_masked_text2: ^0.9.1


  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.7.0
  

  firebase_core: ^3.0.0
  
  cloud_firestore: ^5.0.0
  firebase_auth: ^5.0.0
  firebase_storage: ^12.0.0
  rxdart: ^0.27.7
  path: ^1.9.0

  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5

  user_repository:
    path: packages/user_repository
  pizza_repository:
    path: packages/pizza_repository
  masked_text: ^1.1.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/