name: cart_repository
description: "The Repo that cart pizzas"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #cupertino_icons: ^1.0.6
  #firebase_core: ^3.0.0
  cloud_firestore: ^5.0.0
  #firebase_auth: ^5.0.0
  #equatable: ^2.0.5
  #firebase_storage: ^12.0.0
  #rxdart: ^0.27.7
  #path: ^1.9.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true