// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXUa9SFDzUkREqqGGSJN8891olQmzMdWE',
    appId: '1:645547701129:web:87526f1b8c24a91d4f2758',
    messagingSenderId: '645547701129',
    projectId: 'delivery-app-4e55c',
    authDomain: 'delivery-app-4e55c.firebaseapp.com',
    storageBucket: 'delivery-app-4e55c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHu9N-7gGmJqOPIW1FLgAVt6195jmk3fc',
    appId: '1:645547701129:android:8169ff563bbdcc044f2758',
    messagingSenderId: '645547701129',
    projectId: 'delivery-app-4e55c',
    storageBucket: 'delivery-app-4e55c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQE-6KznFoTkC-l7Ed6r3eKbLD1BRnoQE',
    appId: '1:645547701129:ios:b2168318e59558544f2758',
    messagingSenderId: '645547701129',
    projectId: 'delivery-app-4e55c',
    storageBucket: 'delivery-app-4e55c.appspot.com',
    iosBundleId: 'com.example.deliveryApp',
  );
}
